### ISSUE TITLE
[JOSS review] Initial technical comments

### ISSUE THREAD

**Issue by ml-evs** [bobleesj/cifkit#27]
Hi there, thanks for the submission to JOSS. Here are my initial technical comments; I'll post it here so you can control its visibility going forward, but I will link to it in the overall review issue with a few more general comments.

1. Unfortunately I am struggling to find many CIFs that actually work to test the functionality -- the error messages I am receiving are also not particularly illuminating. I tried:

    - [A random CIF from the COD](https://www.crystallography.net/cod/1100784.html) -- succesfully parsed but visualisation example failed for me.
    - [A random CIF from the Materials Project](https://next-gen.materialsproject.org/materials/mp-2282) -- failed to parse
    - A random CIF from the CSD ([CCDC 824282](http://webcsdoffsite.psds.ac.uk/Search?Ccdcid=824282))-- failed to parse
    - A CIF from the applications paper (Tyvanchuk et al) ([CCDC Number: 2294753](http://webcsdoffsite.psds.ac.uk/Search?Ccdcid=2294753&DatabaseToSearch=Published)) -- failed to parse
 
    These errors seem to relate to preprocessing functions outside of the CIF parser itself, but the errors will not be comprehensible for non-expert users. With the `CifEnsemble` class, all files get moved to `error_others` for me, and in fact, the COD CIF file that worked previously was somehow "corrupted" when being written out to `error_others`.

2. API documentation is lacking (function and class docstrings for the main public methods at a minimum). In particular, its neither clear which parts of CIF are supported (and if anything outside of the [core CIF dictionary](https://www.iucr.org/resources/cif/dictionaries) is supported), nor what to do in the face of errors, nor any discussion of symmetry.

3. I see tox is being used for pinned/testing environments. Given how quickly the Python ecosystem moves, I would suggest either lightly pinning the dependencies in `pyproject.toml` (to e.g., major versions) or at least mention in the documentation how one might install the tested pinned dependencies (i.e., potentially add it as an "extra" that you can install with `pip install .[strict]`, rather than needing another tool in tox). If this package is going to continue to be developed, you may also consider using a tool like [dependabot](https://docs.github.com/en/code-security/getting-started/dependabot-quickstart-guide) to automatically watch out for new breaking versions of your dependencies.

**Comment by bobleesj** [comment]
Thank you, @ml-evs, for your time spent testing and posting the issues here.

1. I will double-check the file sources from the links above. I have recently supported and tested against .cif files sourced from COD, ICSD, PCD, and Materials Studio (Support various .cif formats for v 1.0.3 (COD, ICSD, PCD, Materials Studio) #24), but I will verify them again.

2. I will provide API documentation in the next iteration.

3. I agree with your point about having recently removed the strict pinning as reflected in the current version: [pyproject.toml](https://github.com/bobleesj/cifkit/blob/main/pyproject.toml). I will also explore dependabot and share my feedback.

**Comment by bobleesj** [comment]
Thank you. All of the points have been addressed. 
1.

```python
from cifkit import CifEnsemble, Cif

ensemble_CCDC = CifEnsemble("tests/data/cif/sources/CCDC")
ensemble_COD = CifEnsemble("tests/data/cif/sources/COD")
ensemble_ICSD = CifEnsemble("tests/data/cif/sources/ICSD")
ensemble_MP = CifEnsemble("tests/data/cif/sources/MP")
ensemble_PCD = CifEnsemble("tests/data/cif/sources/PCD")
ensemble_MS = CifEnsemble("tests/data/cif/sources/MS")

print("ensemble_CCDC:", ensemble_CCDC.CN_unique_values_by_best_methods)
print("ensemble_COD:", ensemble_COD.CN_unique_values_by_best_methods)
print("ensemble_ICSD:", ensemble_ICSD.CN_unique_values_by_best_methods)
print("ensemble_MP:", ensemble_MP.CN_unique_values_by_best_methods)
print("ensemble_PCD:", ensemble_PCD.CN_unique_values_by_best_methods)
print("ensemble_MS:", ensemble_MS.CN_unique_values_by_best_methods)

ensemble_CCDC: {16, 11, 12, 13, 14, 15}
ensemble_COD: {10, 4, 7, 8, 682}
ensemble_ICSD: {6, 7, 12, 13}
ensemble_MP: {4, 6}
ensemble_PCD: {6}
ensemble_MS: {19, 9, 10, 11, 12, 13, 14}
```

2. docstrings are provided through the following PRs https://github.com/bobleesj/cifkit/pull/54, https://github.com/bobleesj/cifkit/pull/49https://github.com/bobleesj/cifkit/pull/49, and https://github.com/bobleesj/cifkit/pull/55 and they are available under https://bobleesj.github.io/cifkit/api/

3. removed pinning. Thanks!
