### ISSUE TITLE
Wrong command in the program description file

### ISSUE THREAD

**Issue by dshirya** [bobleesj/cifkit#65]
### Problem

When I tried to use that suggested code:
```
from cifkit import CifEnsemble

ensemble = CifEnsemble("your_folder_path_containing_cif_files")
ensemble.generate_structure_histogram()
```
I've got:
```
AttributeError: 'CifEnsemble' object has no attribute 'generate_structure_histogram'. Did you mean: 'generate_stat_histograms'?
```

### Proposed solution

Change the README file and put correct command: ```generate_stat_histograms```

**Comment by bobleesj** [comment]
Thanks @dshirya I will update the docs!

**Comment by bobleesj** [comment]
@dshirya I double checked the version of 1.0.5 that `generate_stat_histograms` is indeed working as shown below which you can also try using the Google Codelab link.

<img width="641" alt="Screenshot 2024-11-01 at 3 23 38 PM" src="https://github.com/user-attachments/assets/babf4770-a28d-4211-9a0a-9f929385ba7f">

<img width="1057" alt="Screenshot 2024-11-01 at 3 24 58 PM" src="https://github.com/user-attachments/assets/612b8ae2-675c-4a76-9429-656474b4ae98">

Was your package tested using v1.0.5?

**Comment by dshirya** [comment]
Yes, ```generate_stat_histograms``` works right, but in the description you have ```generate_structure_histogram```

**Comment by bobleesj** [comment]
appears `generate_structure_histogram` works? Your code above show that there is a bug with running `generate_structure_histogram`.
